[package]
name = "hyper-http-connector"
version = "0.1.0"
authors = ["Darren Tsung <darren@onesignal.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1.11"
log = "0.4"
tokio-service = "0.1"
trust-dns-resolver = "0.9"
tokio = "0.1"
lazy_static = "1.0"
