[package]
name = "hyper-http-connector"
version = "0.1.0"
authors = ["Darren Tsung <darren@onesignal.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1.11"
log = "0.4"
tokio-service = "0.1"
c-ares-resolver = "4.0"
c-ares = "5.0"
